# Generated by Django 4.2 on 2023-04-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_usuario_nome_alter_formula_delta_alter_formula_x1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='input_value1',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='input_value2',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='input_value3',
        ),
        migrations.AddField(
            model_name='formula',
            name='res1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='res2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='x3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formula',
            name='x1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formula',
            name='x2',
            field=models.IntegerField(default=0),
        ),
    ]
